-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TYPE organizational_form AS ENUM ('IndividualEntrepreneur', 'LimitedLiabilityCompany', 'JointStockCompany');


CREATE TABLE IF NOT EXISTS public.client
(
    id bigint NOT NULL,
    name character varying NOT NULL,
    short_name character varying NOT NULL,
    curr_organizational_form organizational_form NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.bank
(
    id bigint NOT NULL,
    bank_id_code integer NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.deposit
(
    id bigint NOT NULL,
    opening_date timestamp without time zone NOT NULL,
    percent integer NOT NULL,
    period_in_month integer NOT NULL,
    bank_id bigint NOT NULL,
    client_id bigint NOT NULL,
    PRIMARY KEY (id)
    );

ALTER TABLE IF EXISTS public.deposit
    ADD CONSTRAINT bank_id FOREIGN KEY (bank_id)
    REFERENCES public.bank (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.deposit
    ADD CONSTRAINT client_id FOREIGN KEY (client_id)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;